Step 0 gavin
gavinnwang/learnsomething pull request #1
Opened 2023-10-31 14:18 UTC by wry0313

1. What is the purpose of this PR? **This PR aims to fix the bug with risk tracker and pass all tests**
2. What changes did you make? Why? **I changed risk tracker's logic from using += which accumulates previous values of all running sum calculations to = which will let it set total risk to the running sum**
3. What bugs did you find while testing?  **The risk tracker is risk calculation is not working**

1. What was the bug you found?
**The bug was that the risk tracker's logic is wrong. It shouldn't use += as it will accumulates previous values of all running sum calculations.**
2. How did you address it?
**I changed risk tracker's logic from using += which accumulates previous values of all running sum calculations to = which will let it set total risk to the running sum**
3. What did you struggle with?
**I struggled with using prettier with cpp**
5. Is there anything you would change about this step?
**No**

2023-10-31 14:38 UTC, echavemann requested changes

2023-10-31 14:38 UTC, echavemann commented on .vscode/settings.json
> +    "files.associations": {
gitignore

2023-10-31 14:38 UTC, echavemann commented
clangd-format is the way

2023-11-02 23:25 UTC, minnce approved these changes
good work, lgtm :)

2023-11-05 21:57 UTC, merged